import assert from "node:assert/strict";
import {test} from "node:test";
import {readFileSync,existsSync} from "node:fs";
import {registerHooks} from "node:module";
import ts from "typescript";
import React,{Children,isValidElement,type ReactNode} from "react";
import {renderToStaticMarkup} from "react-dom/server";
import {AutomationClient,AUTOMATION_POLL_MS,automationPhrase,automationError,offsetLabel,triggerSummary,openAutomationItem,needsAttention,startAutomationPolling,type AutomationPreview,type AutomationItem,type AutomationOperation,type PollEnvironment} from "../src/automations.ts";
import {JarvisClient} from "../src/jarvis/jarvis.ts";
import {sampleProjects} from "../src/preview-projects.ts";
registerHooks({resolve(specifier,context,next){if(context.parentURL?.includes("/src/")&&specifier.startsWith("./")&&!/\.[a-z]+$/.test(specifier))return next(specifier+(existsSync(new URL(specifier+".tsx",context.parentURL))?".tsx":".ts"),context);return next(specifier,context);},load(url,context,next){if(/\.(css|png)$/.test(url))return {format:"module",shortCircuit:true,source:'export default "synthetic";'};if(url.endsWith(".tsx"))return {format:"module",shortCircuit:true,source:ts.transpileModule(readFileSync(new URL(url),"utf8"),{compilerOptions:{jsx:ts.JsxEmit.ReactJSX,module:ts.ModuleKind.ESNext,target:ts.ScriptTarget.ES2020}}).outputText};return next(url,context);}});
const {default:AutomationsPage}=await import("../src/AutomationsPage.tsx");
const {default:AutomationInbox}=await import("../src/AutomationInbox.tsx");
const {default:AutomationReview}=await import("../src/AutomationReview.tsx");
const {default:TodayPage}=await import("../src/TodayPage.tsx");
const {Sidebar}=await import("../src/App.tsx");
Object.assign(globalThis,{window:globalThis,isTauri:false});
const id="00000000-0000-4000-8000-000000000001";
function item(task:AutomationItem["task"]={kind:"command_prompt",prompt:"Synthetic local prompt",project_alias:null}):AutomationItem{return {version:1,id,automation_id:id,automation_title:"Synthetic reminder",task,triggered_at:1800000000,occurrence_key:"once:2027-01-15T08:00:00Z",status:"pending"};}
function preview(operation:AutomationOperation="create"):AutomationPreview {return {version:1,request_id:id,operation,automation_id:id,before:null,after:{version:1,id,revision:id,payload:{title:"Synthetic full title",enabled:true,trigger:{kind:"daily",hour:8,minute:30,offset_minutes:330},task:{kind:"reminder",message:"Synthetic full first line\nSynthetic full final line"}},created_at:1800000000,updated_at:1800000000,cursor:{last_due:null,condition_true:false,edge:0}},created_at:1800000000,expires_at:1800000300,request_sha256:"a".repeat(64),confirmation_phrase:operation.toUpperCase()+" AUTOMATION "+"a".repeat(64)};}
function buttons(tree:ReactNode):Array<{children?:ReactNode;onClick:()=>void;disabled?:boolean}> {const out:Array<{children?:ReactNode;onClick:()=>void;disabled?:boolean}>=[];Children.forEach(tree,n=>{if(!isValidElement(n))return;const p=n.props as {children?:ReactNode;onClick?:()=>void};if(n.type==="button"&&p.onClick)out.push(p as typeof out[number]);out.push(...buttons(p.children));});return out;}
test("Automations is active in native mode and mount has no provider or mutation calls",()=>{let calls=0;const html=renderToStaticMarkup(React.createElement(AutomationsPage,{client:new AutomationClient(()=>true,async<T>()=>{calls++;return {} as T;})}));assert.match(html,/New automation/);for(const text of ["Due now","Active","Paused","History / recently handled"])assert.ok(html.includes(text));assert.doesNotMatch(html,/Not enabled yet|Coming next|Run All/);assert.equal(calls,0);});
test("static browser automations performs no IPC including evaluation",async()=>{let calls=0;const client=new AutomationClient(()=>false,async<T>()=>{calls++;return {} as T;});assert.match(renderToStaticMarkup(React.createElement(AutomationsPage,{client})),/Static browser preview/);await assert.rejects(client.evaluate());await assert.rejects(client.prepare({operation:"create",automation_id:null,payload:preview().after!.payload}));await assert.rejects(client.acknowledge(id));await assert.rejects(client.dismiss(id));await assert.rejects(client.load());assert.equal(calls,0);});
test("finite client evaluator invokes only the local evaluation command",async()=>{const names:string[]=[];const c=new AutomationClient(()=>true,async<T>(name:string)=>{names.push(name);return {created:[],pending_count:0,audit_recorded:true} as T;});await c.evaluate();assert.deepEqual(names,["evaluate_automations"]);});
test("create prepare does not execute and requires exact confirmation",async()=>{const calls:string[]=[];const c=new AutomationClient(()=>true,async<T>(name:string)=>{calls.push(name);return preview() as T;});const p=await c.prepare({operation:"create",automation_id:null,payload:preview().after!.payload});assert.deepEqual(calls,["prepare_automation_mutation"]);assert.ok(Object.isFrozen(p.after!.payload));await assert.rejects(c.execute(p,"CREATE AUTOMATION wrong"));assert.equal(calls.length,1);await c.execute(p,automationPhrase(p));assert.deepEqual(calls,["prepare_automation_mutation","execute_automation_mutation"]);await assert.rejects(c.execute(p,automationPhrase(p)));});
test("editing invalidates native preview and in-flight preparation",async()=>{const c=new AutomationClient(()=>true,async<T>()=>preview() as T);const p=await c.prepare({operation:"create",automation_id:null,payload:preview().after!.payload});c.invalidate();await assert.rejects(c.execute(p,automationPhrase(p)));let done:((p:AutomationPreview)=>void)|undefined;const slow=new AutomationClient(()=>true,<T>()=>new Promise<T>(resolve=>{done=resolve as (p:AutomationPreview)=>void;}));const pending=slow.prepare({operation:"create",automation_id:null,payload:preview().after!.payload});slow.invalidate();done!(preview());await assert.rejects(pending);});
test("pause resume delete require the same native prepared mutation gate",async()=>{for(const operation of ["pause","resume","delete"] as const){const calls:string[]=[];const c=new AutomationClient(()=>true,async<T>(name:string)=>{calls.push(name);return preview(operation) as T;});const p=await c.prepare({operation,automation_id:id,payload:null});assert.deepEqual(calls,["prepare_automation_mutation"]);await c.execute(p,automationPhrase(p));assert.deepEqual(calls,["prepare_automation_mutation","execute_automation_mutation"]);}});
test("failed mutation is consumed without retry",async()=>{let writes=0;const c=new AutomationClient(()=>true,async<T>(name:string)=>{if(name==="execute_automation_mutation"){writes++;throw "storage";}return preview() as T;});const p=await c.prepare({operation:"create",automation_id:null,payload:preview().after!.payload});await assert.rejects(c.execute(p,automationPhrase(p)));await assert.rejects(c.execute(p,automationPhrase(p)));assert.equal(writes,1);});
test("complete preview includes full content and exact offset",()=>{const p=preview();const html=renderToStaticMarkup(React.createElement(AutomationReview,{preview:p,busy:false,onConfirm(){assert.fail();},onDiscard(){}}));for(const text of ["Synthetic full title","Synthetic full final line","UTC+05:30",p.request_sha256,"Exact confirmation"])assert.ok(html.includes(text));assert.match(html,/disabled=""/);});
test("due items state no action has run and escaped text is inert",()=>{const i=item({kind:"reminder",message:"<script>synthetic()</script>"});const html=renderToStaticMarkup(React.createElement(AutomationInbox,{items:[i]}));assert.match(html,/No action has run/);assert.match(html,/&lt;script&gt;/);assert.doesNotMatch(html,/<script>/);assert.match(html,/Acknowledge/);assert.match(html,/Dismiss/);});
test("Open in Command only navigates and prefills, leaving item pending",()=>{const i=item();const actions:unknown[]=[];openAutomationItem(i,(...args)=>actions.push(args));assert.deepEqual(actions,[["Command",{id,text:"Synthetic local prompt"},null]]);assert.equal(i.status,"pending");});
test("Open Mail and Calendar only navigate without Google reads",()=>{for(const page of ["mail","calendar"] as const){const actions:unknown[]=[];openAutomationItem(item({kind:"review_page",page,message:"Synthetic"}),(...args)=>actions.push(args));assert.deepEqual(actions,[[page==="mail"?"Mail":"Calendar",null,null]]);}});
test("reminder and handled item have no open authority",()=>{let calls=0;openAutomationItem(item({kind:"reminder",message:"Synthetic"}),()=>calls++);openAutomationItem({...item(),status:"dismissed"},()=>calls++);assert.equal(calls,0);});
test("inbox explicit clicks only invoke status handlers or navigation",()=>{const events:unknown[]=[];const tree=AutomationInbox({items:[item()],onOpen:(...args)=>events.push(args),onHandle:(...args)=>events.push(args)});assert.deepEqual(events,[]);const controls=buttons(tree);controls[0].onClick();controls[1].onClick();controls[2].onClick();assert.deepEqual(events,[["Command",{id,text:"Synthetic local prompt"},null],[id,"acknowledged"],[id,"dismissed"]]);});
test("acknowledge dismiss cannot execute a task",async()=>{const calls:string[]=[];const c=new AutomationClient(()=>true,async<T>(name:string)=>{calls.push(name);return true as T;});await c.acknowledge(id);await c.dismiss(id);assert.deepEqual(calls,["acknowledge_automation_item","dismiss_automation_item"]);});
test("sidebar displays pending count and removes Next label",()=>{const html=renderToStaticMarkup(React.createElement(Sidebar,{active:"Today",onNavigate(){},local:true,pendingCount:3}));assert.match(html,/Pending automation attention items/);assert.match(html,/>3<\/small>/);assert.doesNotMatch(html,/>Next</);});
test("Today surfaces due items and snapshot-only attention without calls",()=>{const project={...sampleProjects[0],counts:{...sampleProjects[0].counts,sessions:0},warnings:["Synthetic warning"]};const recent=[{id,created_at:"2027-01-15T08:00:00Z",project_alias:project.alias,action_type:"start_session",status:"pending"}] as const;const html=renderToStaticMarkup(React.createElement(TodayPage,{project,mode:"live-local",recent:[...recent],automationItems:[item()]}));assert.match(html,/Needs attention/);assert.match(html,/already loaded local snapshot/);assert.match(html,/Synthetic reminder/);assert.equal(needsAttention(project,[...recent],1).length,4);});
test("unknown session metadata is not treated as no session",()=>{assert.equal(needsAttention({...sampleProjects[0],counts:{...sampleProjects[0].counts,sessions:null},warnings:[]},[],0).length,0);});
function pollFixture(available=true){let now=0,visible=true,callback:(()=>void)|undefined,cleared=0,calls=0,results=0;const listeners=new Map<string,()=>void>();const env:PollEnvironment={visible:()=>visible,now:()=>now,interval:(fn,ms)=>{assert.ok(ms>=60000);callback=fn;return 1;},clear:()=>{cleared++;},listen:(name,fn)=>{listeners.set(name,fn);return ()=>listeners.delete(name);}};const stop=startAutomationPolling(available,async()=>{calls++;return "synthetic";},()=>results++,()=>assert.fail(),env);return {stop,listeners,tick:()=>callback?.(),clock:(n:number)=>{now=n;},visible:(v:boolean)=>{visible=v;listeners.get("visibilitychange")?.();},calls:()=>calls,results:()=>results,cleared:()=>cleared};}
const settle=async()=>{for(let i=0;i<12;i++)await Promise.resolve();};
test("startup and focus evaluation is throttled to at least 60 seconds",async()=>{const f=pollFixture();await settle();assert.equal(f.calls(),1);f.listeners.get("focus")!();await settle();assert.equal(f.calls(),1);f.clock(60000);f.tick();await settle();assert.equal(f.calls(),2);assert.equal(AUTOMATION_POLL_MS,60000);f.stop();});
test("hidden app pauses timer and visible app safely catches up",async()=>{const f=pollFixture();await settle();f.visible(false);f.clock(120000);f.tick();await settle();assert.equal(f.calls(),1);assert.equal(f.cleared(),1);f.visible(true);await settle();assert.equal(f.calls(),2);f.stop();});
test("poller cleanup stops interval listeners and late UI delivery",async()=>{const f=pollFixture();f.stop();await settle();assert.equal(f.listeners.size,0);assert.equal(f.results(),0);f.clock(120000);f.tick();await settle();assert.equal(f.calls(),1);});
test("browser polling installs no timer listener or IPC",()=>{const f=pollFixture(false);assert.equal(f.calls(),0);assert.equal(f.listeners.size,0);assert.equal(f.cleared(),0);f.stop();});
test("offset summaries are explicit including negative half hours",()=>{assert.equal(offsetLabel(330),"UTC+05:30");assert.equal(offsetLabel(-270),"UTC-04:30");assert.match(triggerSummary({kind:"daily",hour:8,minute:30,offset_minutes:330}),/08:30 at UTC\+05:30/);});
test("raw errors and private content never enter displayed errors",()=>{assert.doesNotMatch(automationError("synthetic private content"),/synthetic private/);assert.match(automationError("limit"),/Nothing was silently discarded/);});
test("M44 production automation surfaces exclude execution and provider primitives",()=>{for(const name of ["automations.ts","AutomationsPage.tsx","AutomationForm.tsx","AutomationReview.tsx","AutomationInbox.tsx"]){const source=readFileSync(new URL("../src/"+name,import.meta.url),"utf8");assert.doesNotMatch(source,/\bfetch\s*\(|XMLHttpRequest|localStorage|sessionStorage|dangerouslySetInnerHTML|access_token|refresh_token|client_secret|prepare_jarvis_request|interpret_jarvis_request|run_command|execute_automation_action|invoke_automation_capability|eval\s*\(|new Function\s*\(/);}});
test("native evaluator has no provider or generic execution imports",()=>{for(const name of ["evaluate.rs","ipc.rs","model.rs","mutations.rs","storage.rs"]){const source=readFileSync(new URL("../src-tauri/src/automations/"+name,import.meta.url),"utf8");assert.doesNotMatch(source,/reqwest|std::process|Command::|prepare_jarvis_request|interpret_jarvis_request|connectors::|execute_automation_action|invoke_automation_capability|run_command|https?:\/\//);}});
test("automation permission has exactly eight narrow local commands",()=>{const source=readFileSync(new URL("../src-tauri/permissions/ghost-automations.toml",import.meta.url),"utf8");const list=source.match(/commands\.allow = \[(.*)\]/)![1].split(",").map(s=>s.trim().replaceAll('"',''));assert.deepEqual(list,["get_automation_status","list_automations","list_automation_inbox","prepare_automation_mutation","execute_automation_mutation","evaluate_automations","acknowledge_automation_item","dismiss_automation_item"]);assert.doesNotMatch(source,/plugin-shell|plugin-http|plugin-fs|run_|interpret_|prepare_jarvis/);});

function jarvisHarness(){
 const source=readFileSync(new URL("../src/jarvis/JarvisCommand.tsx",import.meta.url),"utf8");const ast=ts.createSourceFile("JarvisCommand.tsx",source,ts.ScriptTarget.Latest,true,ts.ScriptKind.TSX);const program=ast.statements.filter(n=>!ts.isImportDeclaration(n)).map(n=>n.getText(ast)).join("\n").replace("export default function JarvisCommand","function JarvisCommand").replace(/^export /gm,"");const output=ts.transpileModule(program,{compilerOptions:{target:ts.ScriptTarget.ES2022,jsx:ts.JsxEmit.React}}).outputText;
 let cursor=0;const cells:any[]=[];let effects:(()=>void)[]=[];const mocks={React,JarvisClient,noSharing:{personal_memory:false,project_memory:false},jarvisError:()=>"error",JarvisPlan:"JarvisPlan",VoiceInput:"VoiceInput",useState:(initial:any)=>{const index=cursor++;if(!cells[index])cells[index]={value:typeof initial==="function"?initial():initial};return [cells[index].value,(v:any)=>{cells[index].value=typeof v==="function"?v(cells[index].value):v;}];},useRef:(v:any)=>{const index=cursor++;return cells[index]??(cells[index]={current:v});},useEffect:(fn:()=>void,deps:any[])=>{const index=cursor++;if(cells[index]?.deps?.every((v:any,i:number)=>v===deps[i])&&cells[index].deps.length===deps.length)return;cells[index]={deps};effects.push(fn);}};
 const Component=new Function(...Object.keys(mocks),output+"\nreturn JarvisCommand;")(...Object.values(mocks));let calls=0;const client=new JarvisClient(()=>true,async<T>()=>{calls++;return {} as T;});let props:any={client,projectAlias:null,projects:[],mode:"live-local"};let tree:ReactNode;
 const render=()=>{cursor=0;tree=Component(props);const pending=effects;effects=[];pending.forEach(f=>f());cursor=0;tree=Component(props);return tree;};
 function nodes(node:ReactNode):React.ReactElement[]{const out:React.ReactElement[]=[];Children.forEach(node,n=>{if(!isValidElement(n))return;out.push(n);out.push(...nodes((n.props as any).children));});return out;}
 return {render,calls:()=>calls,prefill:()=>{props={...props,prefill:{id,text:"Synthetic prefilled prompt"}};render();},nodes:()=>nodes(render())};
}
test("production Command prefill fills text with no prepare or send",()=>{const h=jarvisHarness();h.render();h.prefill();const textarea=h.nodes().find(n=>n.type==="textarea")!;assert.equal((textarea.props as any).value,"Synthetic prefilled prompt");assert.equal(h.calls(),0);});
test("production Command prefill resets sharing off and discards outbound review",()=>{const h=jarvisHarness();h.render();let toggles=h.nodes().filter(n=>n.type==="input"&&(n.props as any).type==="checkbox");(toggles[0].props as any).onChange({target:{checked:true}});assert.equal((h.nodes().filter(n=>n.type==="input"&&(n.props as any).type==="checkbox")[0].props as any).checked,true);h.prefill();toggles=h.nodes().filter(n=>n.type==="input"&&(n.props as any).type==="checkbox");assert.ok(toggles.every(n=>(n.props as any).checked===false));assert.equal(h.calls(),0);assert.doesNotMatch(renderToStaticMarkup(h.render()),/Send reviewed request to OpenAI/);});
