import {useEffect,useRef,useState} from "react";
import AutomationForm from "./AutomationForm.tsx";
import AutomationReview from "./AutomationReview.tsx";
import AutomationInbox from "./AutomationInbox.tsx";
import {AutomationClient,automationError,taskText,triggerSummary,type AutomationDefinition,type AutomationItem,type AutomationPayload,type AutomationPrepare,type AutomationPreview,type AutomationState,type CommandPrefill} from "./automations.ts";
import type {DesktopPage} from "./DesktopPages.tsx";
import type {GhostProject} from "./ghost-snapshot.ts";
export default function AutomationsPage({state={definitions:[],inbox:[]},projects=[],client:supplied,onChanged,onOpen,onHandle}:{state?:AutomationState;projects?:GhostProject[];client?:AutomationClient;onChanged?:()=>Promise<void>;onOpen?:(page:DesktopPage,prefill:CommandPrefill|null,alias:string|null)=>void;onHandle?:(id:string,status:"acknowledged"|"dismissed")=>void}) {
 const [client]=useState(()=>supplied??new AutomationClient());const [editing,setEditing]=useState<AutomationDefinition|null|undefined>(undefined);const [preview,setPreview]=useState<AutomationPreview|null>(null);const [busy,setBusy]=useState(false);const [message,setMessage]=useState("");const working=useRef(false);const mounted=useRef(true);
 useEffect(()=>{mounted.current=true;return ()=>{mounted.current=false;client.invalidate();};},[client]);
 function invalidate(){client.invalidate();setPreview(null);setMessage("");}
 async function perform(work:()=>Promise<void>){if(!client.available()||working.current)return;working.current=true;setBusy(true);setMessage("");try{await work();}catch(e){if(mounted.current)setMessage(automationError(e));}finally{working.current=false;if(mounted.current)setBusy(false);}}
 function prepare(input:AutomationPrepare){invalidate();void perform(async()=>{const p=await client.prepare(input);if(mounted.current)setPreview(p);});}
 function save(payload:AutomationPayload){prepare({operation:editing?"update":"create",automation_id:editing?.id??null,payload});}
 function rows(enabled:boolean){return state.definitions.filter(v=>v.definition.payload.enabled===enabled).map(({definition:d,next_due})=><article key={d.id} className="automation-row"><h3>{d.payload.title}</h3><p>{triggerSummary(d.payload.trigger)}</p><p>{d.payload.task.kind} · {d.payload.enabled?"Active":"Paused"}</p><p>{next_due?"Next expected occurrence: "+new Date(next_due*1000).toISOString():d.payload.trigger.kind==="once"&&d.cursor.last_due?"Already surfaced":d.payload.enabled?"Waiting for local condition":"Paused"}</p><details><summary>Task summary / advanced details</summary><p className="automation-text">{taskText(d.payload.task)}</p><p>Automation {d.id}</p>{d.payload.trigger.kind==="daily"||d.payload.trigger.kind==="weekly"?<p>Exact fixed offset minutes: {d.payload.trigger.offset_minutes}</p>:null}</details><div className="button-row"><button disabled={busy} onClick={()=>{invalidate();setEditing(d);}}>Review / Edit</button><button disabled={busy} onClick={()=>prepare({operation:d.payload.enabled?"pause":"resume",automation_id:d.id,payload:null})}>{d.payload.enabled?"Pause":"Resume"}</button><button disabled={busy} onClick={()=>prepare({operation:"delete",automation_id:d.id,payload:null})}>Delete</button></div></article>);}
 const pending=state.inbox.filter(i=>i.status==="pending");const history:AutomationItem[]=state.inbox.filter(i=>i.status!=="pending");
 return <section className="automations-page"><header className="desktop-page-header"><div><p className="page-eyebrow">Local attention scheduling</p><h1>Automations</h1><p>Reminders and review prompts. You choose every next action.</p></div><button disabled={!client.available()||busy} onClick={()=>{invalidate();setEditing(null);}}>New automation</button></header>
 <p className="notice">Automations run while GHOST is open. Missed schedules are safely caught up when the app is opened again.</p><p>Private plaintext in GHOST_HOME/automations/automations.json and GHOST_HOME/desktop-automation-audit.jsonl. No provider polling, AI calls, OS daemon or automatic task execution.</p>
 {!client.available()?<p className="notice" role="status" aria-live="polite">Static browser preview. Native automation evaluation and mutation are unavailable.</p>:<><AutomationInbox items={pending} onOpen={onOpen} onHandle={onHandle} busy={busy}/>{editing!==undefined&&<AutomationForm key={editing?.id??"new"} definition={editing??undefined} projects={projects} busy={busy} onChange={invalidate} onPrepare={save}/>} {preview&&<AutomationReview key={preview.request_id} preview={preview} busy={busy} onDiscard={invalidate} onConfirm={confirmation=>void perform(async()=>{const current=preview;setPreview(null);const result=await client.execute(current,confirmation);if(mounted.current){setEditing(undefined);setMessage(result.audit_recorded?"Local automation saved. No task has run.":"Local mutation completed; completion audit needs review. Do not replay.");}await onChanged?.();})}/>}<section className="surface"><h2>Active</h2>{rows(true)}</section><section className="surface"><h2>Paused</h2>{rows(false)}</section><section className="surface"><h2>History / recently handled</h2>{history.map(i=><p key={i.id}>{i.automation_title} · {i.status}</p>)}</section></>}
 {message&&<p role="status">{message}</p>}</section>;
}
